### PR TITLE
Activity Leak in PermissionsControllerImpl during Configuration Change Fix

### LINKED ISSUE #181: [Android] Memory Leak in PermissionsControllerImpl due to Activity reference retention during Configuration Changes
## Description

The `PermissionsControllerImpl` implementaiton in the Moko permissions library (v0.19.1 and v0.20.0) causes memory leaks by retaining references to old `Activity` instances during configuration changes (such as screen rotation). 
This is due to the use of `suspendCoroutine` with callback closures that capture the `ActivityResultLauncher`, which in turn holds a reference to the activity context. As a result, the old activity cannot be garbage collected, leading to memory leaks (confirmed with LeakCanary).

## Root Cause

1. `suspendCoroutine` captures the continuation in a closure.
2. The closure references the `ActivityResultLauncher` instance.
3. The launcher holds a reference to the activity context.
4. During configuration changes, the activity is recreated, but the old continuation still holds references to the old activity through the launcher.

## Proposed Solution

A custom implementation (`NoLeakPermissionsController`) avoids this leak by:
- Using `kotlinx.coroutines.flow.MutableSharedFlow` to emit permission request results instead of `suspendCoroutine`.
- Unbinding any existing activity references when binding a new one.
- Passing the activity as a `LifecycleOwner` to the `ActivityResultLauncher` - making sure the launcher is cleared when the activity is destroyed.

Proposed Fix PR : [Link](https://github.com/icerockdev/moko-permissions/pull/182)

## References

- [Android - Get a result from an Activity](https://developer.android.com/training/basics/intents/result#separate)

## Steps to Reproduce

[Super simple sample app to reproduce](https://github.com/0ximDigital/Moko-MemLeak-Sample)

1. Use the default `PermissionsControllerImpl` in an activity.
2. Request permission.
3. While the system permission dialog is visible - Rotate the device or trigger a configuration change.
4. Observe with LeakCanary: the old activity instance is retained.

## Expected Behavior

Old activity instances should be garbage collected after configuration changes.

## Environment

- Moko permissions version: 0.19.1 and 0.20.0

### PR DESCRIPTION
**Pull request by 0ximDigital**
This PR is a proposed fix for the issue https://github.com/icerockdev/moko-permissions/issues/181

### Proposed Solution
The following changes are made to the `PermissionsControllerImpl`:

1. Using MutableSharedFlow to suspend while waiting for the result to emit permission request results instead of using `suspendCoroutine`
2. Unregistering launcher holder if there is any, during the activity destroy lifecycle callback

#### Open to discussion:
At the start of the `bind()` method, there is an `unbindActivity()` method invocation to unbind previously bound Activity if developers mistakenly invoke the bind() method more times for different Activities - Android MultiWindow?

We could throw an exception there instead to signal to developers that they may be making a mistake instead.

### Most Important 
These changes do not change a behaviour of the `PermissionControllerImpl` or the API in any way to keep it backwards compatible.

### CODE REVIEW

File: permissions/src/androidMain/kotlin/dev/icerock/moko/permissions/PermissionsControllerImpl.kt [hunk 1]
```diff
@@ -52,28 +53,20 @@ class PermissionsControllerImpl(
         ) { permissions ->
             val isCancelled = permissions.isEmpty()
 
-            val permissionCallback = permissionCallback ?: return@register
-
             if (isCancelled) {
-                permissionCallback.callback.invoke(
-                    Result.failure(RequestCanceledException(permissionCallback.permission))
-                )
+                permissionRequestResultFlow.tryEmit(PermissionRequestResult.Cancelled)
```
Comment (Alex009) [inline permissions/src/androidMain/kotlin/dev/icerock/moko/permissions/PermissionsControllerImpl.kt]: instead of tryEmit we should use emit i think. in this case if no listeners yet (we in process of activity recreation for example) coroutine will wait result

File: permissions/src/androidMain/kotlin/dev/icerock/moko/permissions/PermissionsControllerImpl.kt [hunk 2]
```diff
@@ -194,12 +177,20 @@ class PermissionsControllerImpl(
...
-private class PermissionCallback(
-    val permission: Permission,
-    val callback: (Result<Unit>) -> Unit
-)
+private sealed class PermissionRequestResult {
+    object Granted : PermissionRequestResult()
+    object Denied : PermissionRequestResult()
+    object DeniedAlways : PermissionRequestResult()
+    object Cancelled : PermissionRequestResult()
+}
```
Comment (Alex009) [inline permissions/src/androidMain/kotlin/dev/icerock/moko/permissions/PermissionsControllerImpl.kt]: this should be simple enum, no need to use sealed here

**Review by Alex009 — CHANGES_REQUESTED** [review]

File: permissions/src/androidMain/kotlin/dev/icerock/moko/permissions/PermissionsControllerImpl.kt (hunk 2 above)
Comment (0ximDigital) [reply permissions/src/androidMain/kotlin/dev/icerock/moko/permissions/PermissionsControllerImpl.kt]: I agree. Will make the change

File: permissions/src/androidMain/kotlin/dev/icerock/moko/permissions/PermissionsControllerImpl.kt (hunk 1 above)
Comment (0ximDigital) [reply permissions/src/androidMain/kotlin/dev/icerock/moko/permissions/PermissionsControllerImpl.kt]: The `tryEmit` implementation works in the same way `suspendCoroutine` worked.

Suppose a listener that invoked `providePermission` has a scope tied to an Activity or has a smaller scope. In that case, the job that holds `providePermission` will cancel (At least it should - if it is not cancelled, they are leaking the Activity), and the result will not be propagated.
In this case, a new invocation of `providePermission` must be called - this will set up a new listener.

So the scope of a listener must be greater than the Activity - ViewModel / Singleton, in which case there will be a listener to collect the permission request result.

So I think we are OK with `tryEmit` in both scenarios. What do you think?

Comment (Alex009) [reply permissions/src/androidMain/kotlin/dev/icerock/moko/permissions/PermissionsControllerImpl.kt]: now i see that you use buffered shared flow, so tryEmit will not lost value white activity in process of recreation. so it's ok

**Review by Alex009 — APPROVED** [review]
